# fly.toml app configuration file generated for gadgetgizmo on 2023-08-14T02:49:05+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gadgetgizmo"
primary_region = "sin"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
